module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: '.',
  testEnvironment: 'node',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: [
    'src/main.ts',
    'src/app.module.ts',
    'src/database/**/*.(t|j)s',
    'src/common/**/*.(t|j)s',
    'src/modules/health/**/*.(t|j)s',
    'src/modules/marketplace/**/*.(t|j)s',
    'src/modules/store/**/*.(t|j)s',
    'src/modules/users/**/*.(t|j)s',
    'src/modules/orders/**/*.(t|j)s',
    'src/modules/drivers/**/*.(t|j)s',
    'src/modules/coupons/**/*.(t|j)s',
    'src/modules/payouts/**/*.(t|j)s',
  ],
  coverageDirectory: '../coverage',
  testPathIgnorePatterns: [
    '/node_modules/',
    // Modulos com codigo-fonte corrompido/truncado. Ver docs/FASE9_CORRUPTED_MODULES.md
    '<rootDir>/test/modules/analytics',
    '<rootDir>/test/modules/compliance',
    '<rootDir>/test/modules/dispatch',
    '<rootDir>/test/modules/document-verification',
    '<rootDir>/test/modules/face-check',
    '<rootDir>/test/modules/loyalty',
    '<rootDir>/test/modules/rental',
    '<rootDir>/test/modules/services-catalog',
    '<rootDir>/test/modules/starter-kit',
    '<rootDir>/test/modules/support',
    '<rootDir>/test/modules/tracking',
    '<rootDir>/test/modules/zones',
  ],
};
